<template>
    <div>
        <h2 class="main-heading">
            {{ lang==='en'? 'Forbidden Products':'Productos Prohibidos' }} <br> <br>
        </h2>
        <p class="snippet">
            {{ lang==='en'? 'These include any item with alcohol listed as a first ingredient, as well as any quantity of FLAMMABLE, EXPLOSIVE or CORROSIVE material.':'Estos incluyen cualquier artículo que contenga alcohol como primer ingrediente, así como cualquier cantidad de material INFLAMABLE, EXPLOSIVO o CORROSIVO.' }} <br>
            {{ 
                lang==='en'?
                'PLEASE DO NOT SHIP THESE PRODUCTS TO YOUR MIAMI ADDRESS AS THEY CANNOT BE SHIPPED TO YOUR COUNTRY AND YOU WILL NEED TO PAY FOR THEIR DESTRUCTION OR THE COST OF RETURNING THEM TO THE SHIPPER.'
                :'NO ENVÍE ESTOS PRODUCTOS A SU DIRECCIÓN DE MIAMI YA QUE NO SE PUEDEN ENVIAR A SU PAÍS Y DEBERÁ PAGAR POR SU DESTRUCCIÓN O EL COSTO DE DEVOLVERLOS AL REMITENTE.'
            }} <br>
        </p>
        <RatesTable :list="info.products" :hasHeader="true" :colspan="2"/>
        
        <RatesInformation :list="info.list1" />
        
        <h2 class="main-heading">
            {{ lang==='en'?'Special Handling Products':'Productos de manejo especial' }}
        </h2>
        <p class="snippet" v-html="info.specialDesc"></p>
        
        <RatesTable :list="info.products1" :hasHeader="true"/>
        
        <p class="snippet">
            {{ lang==='en'?'*Permit costs are variable and will depend on the amount and assortment of products.':'*Los costos de los permisos son variables y dependerán de la cantidad y surtido de productos.' }}<br><br>
            {{ lang==='en'?'Without this documentation, country entry notification will be automatically rejected.':'Sin esta documentación, la notificación de ingreso al país será automáticamente rechazada.' }}<br><br>
            {{ lang==='en'?'These products are required to pay a USD $5.00 permit minimum, in addition to freight and duty charges generated by the merchandise.':'Estos productos están obligados a pagar un mínimo de permiso de USD $5.00, además de los gastos de flete y derechos que genera la mercancía.' }}
        </p>
        
        <RatesTable :list="info.products2" :hasHeader="true" :colspan="2"/>
        
        <RatesInformation :list="info.list2" />

        <h2 class="main-heading">
            {{ lang==='en'?'Processes and permits':'Procesos y permisos' }}
        </h2>
        <p class="snippet">
            {{ 
                lang==='en'?
                'These items may have local restrictions or require special permits to enter the country.'
                :'Estos artículos pueden tener restricciones locales o requerir permisos especiales para ingresar al país.'
             }}
        </p>
        <RatesTable :list="info.products3" :hasHeader="true"/>

        <h2 class="main-heading">
            {{ lang==='en'?'Replicas':'Réplicas' }}
        </h2>
        <p class="snippet">
            {{ lang==='en'? 'AS STIPULATED BY LOCAL CUSTOMS, IT IS FORBIDDEN TO IMPORT PRODUCTS THAT ARE CONSIDERED REPLICAS, AND IF THESE REACH THE COUNTRY THEY WILL BE CONFISCATED BY PANAMIAN CUSTOMS.':'SEGÚN LO ESTIPULA LA ADUANAS LOCALES, ESTÁ PROHIBIDO IMPORTAR PRODUCTOS CONSIDERADOS RÉPLICAS, Y SI LLEGAN AL PAÍS SERÁN DECOMISADOS POR LA ADUANAS PANAMEÑAS.' }} <br><br>
            {{ lang==='en'? 'If you have an updated health registry (up-to-date and approved before the governing entity), you must present this document at our offices, in order to help you speed up the processing of your merchadise.':'Si cuentas con un registro sanitario actualizado (al día y aprobado ante el ente rector), deberás presentar este documento en nuestras oficinas, con el fin de ayudarte a agilizar el trámite de tu mercadería.' }}
        </p>

    </div>
  
</template>

<script setup>

const store = useStore();
const { lang } = storeToRefs(store);

const en_info = ref({
    products:[
        ['These items may not be transported to the destination country:'],
        ['Ammunition and firearms ','Lighters'],
        ['Any item with alcohol listed as its first ingredient	','Wet-cell batteries'],
        ['Cleaning solutions	','Poisons'],
        ['Fireworks	','Pressure containers'],
        ['Gasoline	','Matches'],
        ['Tear gas or pepper spray	','Gas powered tools'],
        ['Dietary supplements that has the active element  known as 1,3- Dimethylamylamine (DMAA) or other equivalent chemical names, for example : Geranium extract, methylhexanamine, methylhexanamine, etc.	','Dry or preserved plants and branches'],
        ['Seeds	','Plants'],
        ['Radio controls	','Tobacco, cigarettes, nicotine gum'],
        ['e-cigarettes	',''],
        ['Animal products	','Drugs'],
        ['Narcotics	','Live animals,'],
        ['Liquor	','Highly valuable items'],
        ['Batteries	 ',''],
    ],
    list1:[
        'Aeropost reserves the right to reject shipment reception, were there proof they have been open, manipulated and/or damaged prior to arrival.  Aeropost offers a service per shipment and does not offer a consolidation service. Aeropost does not transport cash, drugs or any other forbidden items. Aeropost is responsible for reporting these transgressions before the corresponding authorities.',
        'Shipments may be retained in the Miami address for up to 60 (sixty) days, due to but not limited to pending payment accounts, additional preparations for the shipment process, or reception of shipments with name, address and/or consumer request errors. Aeropost reserves the right to destroy or process, at its own discretion, any shipment that was left unclaimed or stored for over 60 (sixty) days in the Miami address or in Aeropost’s facilities in the destination country.',
    ],
    specialDesc:`
        <b>Defined as small quantities of personal use items.</b> <br><br>
        All products, regardless of them being transported in a box containing other items, must pay a variable value permit, based on product type and amounts, to the ruling entity in force, in addition to merchadise freight and taxes. Amount-based restrictions of this type of products are:<br><br>
        - Food (up to 5 kilos), 3 times a year only.<br>
        - Supplements and vitamins (up to 3 kilos), 3 times a year only.<br><br>
        Due to security measures, these products travel as a consolidated shipment, once a month, and have a surcharge of USD $15.00, additional to import duty costs.<br><br>
        Aeropost carries out this process on behalf of the customer; however, it is mandatory that the customer submits the following documentation to Customer Service every time they process this kind of imports:<br><br>
    `,
    products1:[
        ['FOOD PROCESSING REQUIREMENTS (AUPSA)','DRUGS AND PHARMACY PROCESSING REQUIREMENTS'],
        ['Copy of ID','Copy of ID'],
        ['Image of the product','Image of the product'],
        ['Product specifications (technical label)','Product specifications (technical label)'],
        ['Product purchase invoice','Product purchase invoice'],
        ['','Amounts under 5 kg (11 lb) only'],
        ['','Signed original letter, detailing merchadise use and general specs. To download the letter format (in Spanish), please <a href="" class="text-blue">click here</a>'],
        ['<b>Considerations:</b> <br>- Processing takes 3 to 5 business days.<br>- Personal use amounts only.', '<b>Considerations</b>:<br>- Processing takes 15 to 20 business days.<br>- Personal use amounts only.']
    ],
    products2:[
        ['These items may be transported but are limited:'],
        ['Aerosol cans	','Nail polish'],
        ['Beauty powders	','Aerosol cans'],
        ['Beauty products	','Oil candles'],
        ['Creams	','Perfumes'],
        ['Gels	','Sunblock'],
        ['Non-corrosive cleaning solutions	','Sweetener, food flavoring and coloring products'],
        ['Mouthwash	 ','Cars shocks'],
        ['Hoverboards',''],
    ],
    list2:[
        'Due to safety reasons, products considered of the special handling variety travel as a consolidated shipment, they are shipped once a month and pay a surcharge of USD $15.00, regardless of import duty and special permit costs.'
    ],
    products3:[
        ['Product','	Permit','	Processing Time'],
        ['Wood','	Anam, Quarantine	','7 business days'],
        ['Medication','     Pharmacies and drugs (present prescription and copy of ID or Passport)	','30 days'],
        ['Vitamins','	AUPSA	','5 days'],
        ['Supplements','	AUPSA	','5 days'],
        ['Food','	AUPSA	','5 days'],
    ]
});
const es_info = ref({
    products:[
        ['Estos artículos no pueden ser transportados al país de destino:'],
        ['Municiones y armas de fuego', 'Mecheros'],
        ['Cualquier artículo con alcohol incluido como su primer ingrediente', 'Baterías de celda húmeda'],
        ['Soluciones de limpieza','Venenos'],
        ['Fuegos artificiales','Contenedores a presión'],
        ['Gasolina','Fósforos'],
        ['Gas lacrimógeno o gas pimienta', 'Herramientas a gas'],
        ['Suplementos dietéticos que tienen el elemento activo conocido como 1,3-Dimetilamilamina (DMAA) u otros nombres químicos equivalentes, por ejemplo: extracto de geranio, metilhexanamina, metilhexanamina, etc.', 'Plantas y ramas secas o conservadas'],
        ['Semillas','Plantas'],
        ['Radiocontroles', 'Tabaco, cigarrillos, chicles de nicotina'],
        ['cigarrillos electrónicos',''],
        ['Productos animales','Medicamentos'],
        ['Narcóticos', 'Animales vivos'],
        ['Licor','Artículos de gran valor'],
        ['Baterías',''],
    ],
    list1:[
            'Aeropost se reserva el derecho de rechazar la recepción de los envíos, en caso de que se compruebe que han sido abiertos, manipulados y/o dañados antes de su llegada. Aeropost ofrece un servicio por envío y no ofrece un servicio de consolidación. Aeropost no transporta dinero en efectivo, drogas o cualquier otro artículo prohibido. Aeropost es responsable de denunciar estas transgresiones ante las autoridades correspondientes.',
            'Los envíos podrán ser retenidos en la dirección de Miami hasta por 60 (sesenta) días, debido, entre otros, a cuentas de pago pendientes, preparativos adicionales para el proceso de envío, o recepción de envíos con errores de nombre, dirección y/o solicitud del consumidor. Aeropost se reserva el derecho de destruir o procesar, a su discreción, cualquier envío que haya quedado sin reclamar o almacenado por más de 60 (sesenta) días en la dirección de Miami o en las instalaciones de Aeropost en el país de destino.',
        ],
    specialDesc:`
        <b>Definido como pequeñas cantidades de artículos de uso personal.</b> <br><br>
            Todos los productos, independientemente de que sean transportados en una caja que contenga otros artículos, deben pagar un permiso de valor variable, según el tipo de producto y montos, a la entidad rectora vigente, además de los fletes e impuestos de la mercadería. Las restricciones por cantidad de este tipo de productos son:<br><br>
            - Alimentos (hasta 5 kilos), solo 3 veces al año.<br>
            - Suplementos y vitaminas (hasta 3 kilos), solo 3 veces al año.<br><br>
            Por medidas de seguridad, estos productos viajan como un envío consolidado, una vez al mes, y tienen un recargo de USD $15.00, adicional al costo de los aranceles de importación.<br><br>
            Aeropost realiza este proceso en nombre del cliente; sin embargo, es obligatorio que el cliente presente la siguiente documentación al Servicio de Atención al Cliente cada vez que tramite este tipo de importaciones:<br><br>
    `,
    products1:[
        ['REQUISITOS DE PROCESAMIENTO DE ALIMENTOS (AUPSA)','REQUISITOS DE PROCESAMIENTO DE MEDICAMENTOS Y FARMACIA'],
        ['Copia de DNI','Copia de DNI'],
        ['Imagen del producto','Imagen del producto'],
        ['Especificaciones del producto (etiqueta técnica)','Especificaciones del producto (etiqueta técnica)'],
        ['Factura de compra del producto','Factura de compra del producto'],
        ['','Cantidades inferiores a 5 kg (11 lb) solamente'],
        ['','Carta original firmada, que detalla el uso de la mercancía y las especificaciones generales. Para descargar el formato de carta (en español), <a href="" class="text-blue">haga clic aquí</a>'],
        ['<b>Consideraciones:</b> <br>- El procesamiento demora de 3 a 5 días hábiles.<br>- Solo cantidades para uso personal.', '<b>Consideraciones</b>:<br>- El procesamiento demora 15 a 20 días hábiles.<br>- Cantidades de uso personal solamente.']
    ],
    products2:[
        ['Estos artículos pueden ser transportados pero están limitados:'],
        ['Latas de aerosol', 'Esmalte de uñas'],
        ['Polvos de belleza', 'Latas de aerosol'],
        ['Productos de belleza','Velas de aceite'],
        ['Cremas', 'Perfumes'],
        ['Gels','Bloqueador solar'],
        ['Soluciones de limpieza no corrosivas', 'Productos edulcorantes, aromatizantes y colorantes alimentarios'],
        ['Enjuague bucal', 'Cars shocks'],
        ['Aerotablas',''],
    ],
    list2:[
        'Por razones de seguridad, los productos considerados de la variedad de manejo especial viajan como un envío consolidado, se envían una vez al mes y pagan un recargo de USD $ 15.00, independientemente de los costos de derechos de importación y permisos especiales.'
    ],
    products3:[
        ['Producto', 'Permiso', 'Tiempo de procesamiento'],
        ['Madera', 'Anam, Cuarentena', '7 días hábiles'],
        ['Medicación', 'Farmacias y medicamentos (presentar receta y copia de DNI o Pasaporte)', '30 días'],
        ['Vitaminas', 'AUPSA', '5 días'],
        ['Suplementos', 'AUPSA', '5 días'],
        ['Alimentación', 'AUPSA', '5 días'],
    ]
});

const info = computed(()=>{ return lang.value==='en'? en_info.value:es_info.value })

</script>

<style scoped>
.snippet{
    @apply text-blue mb-4;
}
</style>
